### PR TITLE
Develop First Version

### PR DESCRIPTION
**Pull request by opming7788**
請老師幫忙檢查 
使用 screen 啟動 Uvicorn維持ssh斷線後，Uvicorn還能繼續跑的功能
@app.get("/api/mrts"
http://13.230.3.203/api/mrts
@app.get("/api/attraction"
http://13.230.3.203/api/attraction/38
@app.get("/api/attractions/"
http://13.230.3.203/api/attractions/?page=0&keyword=北投

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
nextPage field of the last page should be null. For example, nextPage of http://13.230.3.203/api/attractions/?page=4 and http://13.230.3.203/api/attractions/?page=0&keyword=%E5%8C%97%E6%8A%95 should be null.

**Comment by opming7788** [comment]
已改好，再請老師review
@app.get("/api/mrts"
http://13.230.3.203/api/mrts
@app.get("/api/attraction"
http://13.230.3.203/api/attraction/38
@app.get("/api/attractions/"
[http://13.230.3.203/api/attractions/?page=0&keyword=北投](http://13.230.3.203/api/attractions/?page=0&keyword=%E5%8C%97%E6%8A%95)

**Review by cwpeng — APPROVED** [review]
OK. Done. But what's your name?

**Comment by opming7788** [comment]
我是陳哲明，奇怪我上一次merge時候有留言名字過，github留言會刪除喔?

**Comment by cwpeng** [comment]
OK. Every pull request is separated. Just check if this page has your name. I won't check your history information.

**Pull request merged**
